### PR TITLE
Patch 2.5 - more fixes

### PR DESCRIPTION
**Pull request by zeddicus-pl**
With my last fix I incorrectly assumed that the `readItems` is an entry point to all items reading. Because of that the patch 2.5 items were not read from stash, corpse etc.

In this fix I moved the constants-tuning call into `readItem`.

I also added some caching for the tuned constants, because the way I initially coded it was to deep-copy the old into new constants, and that takes time. It is a deep copy for a reason - you don't want to change the constants globally by reference, in case you want to read multiple versions in the same application run.

### CODE REVIEW

**Comment by dschu012** [comment]
I'll merge this, but I think a `99_constant_data.ts` needs to be created to sit along side `96_constant_data.ts`. (96 here == version 0x60 i.e. legacy d2). Previously I've used `parser.spec.ts` to create this file on older versions but w/ D2R and the new jsons that "test" probably won't work. Anyways this is just how I think some things should be fixed (instead of the hack in `items.ts` (`_correctConstantsForVersion`). I don't really have time to support this project anymore, hopefully I'll find time soon to update it to 2.5.

**Comment by dschu012** [comment]
Looks like you might still be making changes, let me know if/when you want me to merge.

**Comment by zeddicus-pl** [comment]
@dschu012 I think I'm done, it now works fine in my app.

**Comment by zeddicus-pl** [comment]
@dschu012 I did want to create the 99_constant_data because the constants is a param to most functions, and in many places the decision to use 96 or 96 must be done dynamically based on the version in the header. Like when reading stash - I don't know the version of the stash before the header is read.

**Pull request merged**
